name: Lint

on: [push]

jobs:
  lint:
    name: Lint and type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Check coding style with black
        run: black . --check

      - name: Check type hints with pyright
        run: pyright .
